// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IssuranceConsumer.Infrastructure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace IssuranceConsumer.Infrastructure.Models.Configurations
{
    public partial class MemberConfiguration : IEntityTypeConfiguration<Member>
    {
        public void Configure(EntityTypeBuilder<Member> entity)
        {
            entity.HasKey(e => e.MemberId).HasName("PK__member__42A68F2718FA9779");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Member> entity);
    }
}
