// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IssuranceConsumer.Infrastructure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace IssuranceConsumer.Infrastructure.Models.Configurations
{
    public partial class PrizeConfiguration : IEntityTypeConfiguration<Prize>
    {
        public void Configure(EntityTypeBuilder<Prize> entity)
        {
            entity.HasKey(e => e.PrizeCode).HasName("PK__prize__DDAA77B2E3DF71FD");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Prize> entity);
    }
}
