// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FakeDataGenerator.Models;

[Table("prize")]
public partial class Prize
{
    [Key]
    [Column("Prize_Code")]
    [StringLength(100)]
    [Unicode(false)]
    public string PrizeCode { get; set; }

    [Required]
    [Column("DESCRIPTION")]
    [StringLength(100)]
    [Unicode(false)]
    public string Description { get; set; }
}