// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IssuranceConsumer.Infrastructure.Models.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace IssuranceConsumer.Infrastructure.Models;

public partial class InsurancesContext : DbContext
{
    public InsurancesContext()
    {
    }

    public InsurancesContext(DbContextOptions<InsurancesContext> options)
        : base(options)
    {
        
    }

   

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<Prize> Prizes { get; set; }

     
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.MemberConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PrizeConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
